### ISSUE TITLE
Logger message in console about dropping proj plugin

### ISSUE THREAD

**Issue by syamilmj** [g-andrade/locus#49]
https://github.com/g-andrade/locus/blob/master/rebar.config.script#L9

This seems to run on every instance of the console.

```
[info] Dropping proj plugin 'rebar3_hank' 1.4.0
```

Not sure if related to #35 but seems similar.

**Comment by g-andrade** [comment]
Ohh, this happens on older OTP versions which `rebar3_hank` is no longer compatible with[*]. There's no reason to display it on `locus` consumers since it's a dev-only plugin. I'll look into ways of conditioning it to only when `locus` is being built directly, if not possible I'll remove the message altogether.

[*]: Edit: also on OTP 25 if it doesn't have maybe expressions enabled

**Comment by g-andrade** [comment]
For reference, here's the source of the message:
https://github.com/g-andrade/locus/blob/2.3.10/rebar.config.script
